### ISSUE TITLE
你好请问我这个错误是怎么回事，是header填写错误了吗，可以给一个大概的格式吗 

### ISSUE THREAD

**Issue by CreamK** [akuticlouds/actions-youth#1]

**Comment by CreamK** [comment]
========== 共1个中青账号  =============

============ 脚本执行-国际标准时间(UTC)：12/25/2020, 12:50:33 PM  =============

============ 脚本执行-北京时间(UTC+8)：12/25/2020, 8:50:33 PM  =============

-------------------------

开始【中青看点1】

❗️中青看点, 错误!
SyntaxError: Unexpected token & in JSON at position 1864
    at JSON.parse (<anonymous>)
    at /home/runner/Scripts/Task/youth.js:246:27
    at new Promise (<anonymous>)
    at sign (/home/runner/Scripts/Task/youth.js:243:12)
    at /home/runner/Scripts/Task/youth.js:157:9
    at Object.<anonymous> (/home/runner/Scripts/Task/youth.js:210:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

🔔中青看点, 结束! 🕛 0.019 秒

**Comment by CreamK** [comment]
解决了，是我cookie填错了，谢谢
